status = [
  "test (1.%, ubuntu-latest, x86, 1)",
  "test (1.%, ubuntu-latest, x86, 2)",
  "test (1, ubuntu-latest, x86, 1)",
  "test (1, ubuntu-latest, x86, 2)",
  "test (1.%, ubuntu-latest, x64, 1)",
  "test (1.%, ubuntu-latest, x64, 2)",
  "test (1, ubuntu-latest, x64, 1)",
  "test (1, ubuntu-latest, x64, 2)",
  "test (1.%, macOS-latest, x64, 1)",
  "test (1.%, macOS-latest, x64, 2)",
  "test (1, macOS-latest, x64, 1)",
  "test (1, macOS-latest, x64, 2)",
  "test (1.%, windows-latest, x64, 1)",
  "test (1.%, windows-latest, x64, 2)",
  "test (1, windows-latest, x64, 1)",
  "test (1, windows-latest, x64, 2)",
  "Turing.jl"
]
delete_merged_branches = true
# Require at least on approval of a project member.
required_approvals = 1
# Squash commits before merging.
use_squash_merge = true
# Uncomment this to use a two hour timeout.
# The default is one hour.
#timeout_sec = 7200
