[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
DynamicPPL = "0.23"
MLUtils = "0.3"
Distributions = "0.25"
Documenter = "0.27"
Setfield = "0.7.1, 0.8, 1"
StableRNGs = "1"
